In [30]:
import pandas as pd
import plotly.express as px

# Exercise

Now that we have learned some of the basics of python, we should practice how to use this new superpower. We have here prepared a loosely guided exercise that focusses on data exploration and visualization on two example datasets, one on strokes and one on cirrhosis. You can also explore a dataset of your choosing, though the questions are prepared with the example datasets in mind.

Here you can see the [metadata](https://www.kaggle.com/datasets/fedesoriano/cirrhosis-prediction-dataset) for the cirrhosis dataset which describes what each of the columns are. For the stroke data the meaning of the columns is more straightforward.

## 1. Data Loading

We will start with the **stroke** dataset. You can find it on the GitHub repository under Exercise/datasets. Load the stroke data into colab by using one of the two approaches detailed below and assign it to variable name ```data```.

### Solution: 1.1 Loading the data

**Option 1:**

Use the pandas csv reader with a link to the data on GitHub. To do this, go to the github repository, find the stroke dataset and click on the 'raw' button. Copy that link and enter it as the file path in pandas csv reader.

Go to the github repository, find the dataset you want to work with and click on the 'raw' button. Copy the link and enter it as the file directory in pandas csv reader.

In [31]:
# Stroke dataset
data = pd.read_csv('https://raw.githubusercontent.com/Center-for-Health-Data-Science/PythonTsunami/refs/heads/2024_Oct/Exercise/datasets/healthcare-dataset-stroke-data.csv')
data

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

**Option 2**

Manually load the dataset into colab and then read it with the pandas csv reader. See steps below:

1. go to the left side bar and click on the folder icon
2. click on data upload
3. select dataset from your computer
4. call pandas csv reader with the name of the dataset (see below)

In [32]:
#data = pd.read_csv('cirrhosis.csv')
#data

### 1.2 Solution: First look

Have a first look at the data. There are some neat built-in pandas functions to get an initial understanding of the data, i.e. by using the info function: `df.info()`, or the use pandas `df.describe()` function.

In [33]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [34]:
data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
id,5110.0,36517.829354,21161.721625,67.00,17741.250,36932.000,54682.00,72940.00
age,5110.0,43.226614,22.612647,0.08,25.000,45.000,61.00,82.00
hypertension,5110.0,0.097456,0.296607,0.00,0.000,0.000,0.00,1.00
heart_disease,5110.0,0.054012,0.226063,0.00,0.000,0.000,0.00,1.00
avg_glucose_level,5110.0,106.147677,45.283560,55.12,77.245,91.885,114.09,271.74
bmi,4909.0,28.893237,7.854067,10.30,23.500,28.100,33.10,97.60
stroke,5110.0,0.048728,0.215320,0.00,0.000,0.000,0.00,1.00

Questions you might want to answer here:
- **What different types of columns do you have?**
  We have integer columns (`int64`), object columns (`object`) and float columns with decimals (`float64`)
- **Is there a column that describes a variable that can be understood as an 'outcome'? Which one?**
  The `stroke` variable in the stroke dataset or the `Stage` variable in the cirrohsis dataset.
- **How many values does each variable, i.e. column, have and what are some preliminary statistics of the features?**
  The `count` column of the `describe()` method will give us the count of values (if there are less than expected it means there are NA values). We can get information of the numeric columns, such as mean, standard deviation, minimum value, 25% percentile, 50% percentile, 75% percentile and the max.

It helps to know which column is the outcome variable. In the stroke datasets (and many others!) the outcome variable is coded as a numerical variable. However, during analysis it should be interpreted as categorical.

Identify the column of the outcome variable and change its type to "cateory", then use `info()` on the dataframe again. Has it changed?

In [35]:
# We change the type of a column using the .astype() method
data["stroke"] = data["stroke"].astype("category")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   category
dtypes: category(1), float64(3), int64(3), object(5)
memory usage: 444.4+ KB

We also note that the columns `hypertension` and `heart_disease` consist on only 0s and 1s, meaning "No" and "Yes", respectively. We should probably also change these variables from `int64` to `category`.

In [36]:
data["hypertension"] = data["hypertension"].astype("category")
data["heart_disease"] = data["heart_disease"].astype("category")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   category
 4   heart_disease      5110 non-null   category
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   category
dtypes: category(3), float64(3), int64(1), object(5)
memory usage: 374.8+ KB

## 2. Exploratory analysis

Get to know your data better. If you want to first visually inspect the data it can help to explore with some plots.

### 2.1 Solution: Violin plots and histograms


Consider you dataframe columns that are not the outcome variable. How are the measurements distributed?

To study the distributions we want to make **violin plots** of variables, i.e. data columns, that are numeric and **histograms** of the variables that are strings/categorical.

To check for the data type of a column, have a look at how data types are specified in `dataframe.dtypes`. Then check the data type of each column. Remember a column is a **pandas `Series`**, so it has a `dtype` attribute (only dataframes have `dtypes`!).

You can start by figuring out how to make a plot of the data in one column. Once you have that, make one plot for each column that is numeric or a string (except the outcome). This is a repetitive task, so it is ideally suited for a loop. Remember to use `fig.show()` to actually display your plots.

**Pro version**: Some columns are not actually predictors, such as a the ID column. You can identify these columns i.e. by seeing that each of their values is unique (this would be very unlikely for a measured variable). Skip them when making the plots.

In [37]:
# for loop to iterate through all the columns
for col_name in data.columns: 
    # the id column is not necessary to plot since it is all unique values per row
    if col_name == "id":
        # the continue statement will skip the iteration and go to the next column 
        continue 
    # by using the dtype method we can check the type of the column. If it is numeric, do a violin plot
    elif data[col_name].dtype == 'int64' or data[col_name].dtype == 'float64': 
        # make a violin plot with boxplot in the middle and show all data points. Also, add a title with the name of the variable
        fig = px.violin(data, y=col_name, title = col_name, 
                        box = True, points = "all")
        fig.show()
    else:
        # make a histogram plot. Also, add a title with the name of the variable and separate by the different values
        fig = px.histogram(data, x=col_name, title = col_name, color = col_name)
        fig.show()

We could also choose to color the plot by the outcome variable, stroke, so we get two plots for the two different outcomes.

In [38]:
# for loop to iterate through all the columns
for col_name in data.columns: 
    # the id column is not necessary to plot since it is all unique values per row
    if col_name == "id" or col_name == 'stroke':
        # the continue statement will skip the iteration and go to the next column 
        continue 
    # by using the dtype method we can check the type of the column. If it is numeric, do a violin plot
    elif data[col_name].dtype == 'int64' or data[col_name].dtype == 'float64': 
        # make two violin plots, one for stroke == 0 and one for stroke == 1
        fig = px.violin(data, y=col_name, title = col_name, 
                        color = 'stroke')
        fig.show()
    else:
        # make a histogram plot. Also, add a title with the name of the variable and separate by stroke
        # we may want to add histnorm = probability to be able to compare proportions between stroke and non-stroke
        fig = px.histogram(data, x=col_name, title = col_name, color = 'stroke', barmode = 'group')
        fig.show()

### 2.2 Solution: Correlation coefficients

Plot the correlation coefficients of all numerical features:

1. Use the method `corr()` on the dataframe. What is the result?

In [39]:
# We obtain a correlation matrix between the numerical columns in our data frame
data.corr(numeric_only=True)

                         id       age  avg_glucose_level       bmi
id                 1.000000  0.003538           0.001092  0.003084
age                0.003538  1.000000           0.238171  0.333398
avg_glucose_level  0.001092  0.238171           1.000000  0.175502
bmi                0.003084  0.333398           0.175502  1.000000

2. Now use a heatmap to show the correlation coefficients graphically.
3. Try some different options to make your heatmap look nicer.

In [40]:
px.imshow(data.corr(numeric_only=True),
            text_auto = '.2f', # Put values inside each cell with 2 decimals
            color_continuous_scale='RdBu_r', # use the Reversed color scale RedBlue
            range_color=[-1,1]) # Specify the range of colors

### 2.3 Solution: Scatter plot

Make a scatter plot of the two variables with the highest correlation. Divide the plots by the outcome variable and add marginal plots and a trendline:

1. Find the pair of variables that has the highest correlation with each other and make a scatter plot of them.

2. Divide the scatter plot into two by the outcome variable. Have a look at `facet` and the visualization lecture if you have trouble.

3. Add marginal distributions and a trendline.

In [41]:
# The strongest correlation with between bmi and age
outcome = "stroke"
px.scatter(data, x = "bmi", y = "age", color = outcome,
           trendline = "ols", facet_row = outcome, marginal_y = "box")

## 3. Data cleaning

Now, we switch the [**cirrhosis dataset**]('https://raw.githubusercontent.com/Center-for-Health-Data-Science/PythonTsunami/spring2022/Exercise/datasets/cirrhosis.csv').

We will investigate what data is missing and try to impute it.

A word of caution:

Note that imputation is a __complex subject__ and whether it makes sense to do it and the method used highly depend on the data set. Sometimes, the mean of a value across all non-missing observations is a good approximation for the missing value. On the other hand, if you have a column that says whether or not the person was treated with the drug or the placebo we have no good way to guess which treatment the person received. Replacing missing values in this column with the most common value (which is that they did get the drug) will produce extremely __wrong data__ and lead you to __wrong conclusions__. Do not do that!

### 3.0 Solution: Load the data

Load in the cirrhosis dataset using one of the two methods you used earlier for the stroke data. Change as well the outcome variable to a type "category".

In [42]:
data = pd.read_csv('https://raw.githubusercontent.com/Center-for-Health-Data-Science/PythonTsunami/refs/heads/2024_Oct/Exercise/datasets/cirrhosis.csv') # load the data

# as before, we need to change the outcome variable to "category" since it is not really an integer,  but more like Stage 1, Stage 2, etc.
data["Stage"] = data["Stage"].astype("category") 

data

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,414,681,D,NaN,24472,F,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174.0,10.9,3.0
414,415,1103,C,NaN,14245,F,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180.0,11.2,4.0
415,416,1055,C,NaN,20819,F,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143.0,9.9,3.0
416,417,691,C,NaN,21185,F,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269.0,10.4,3.0
417,418,976,C,NaN,19358,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350.0,10.6,4.0

In [43]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             418 non-null    int64
 1   N_Days         418 non-null    int64
 2   Status         418 non-null    object
 3   Drug           312 non-null    object
 4   Age            418 non-null    int64
 5   Sex            418 non-null    object
 6   Ascites        312 non-null    object
 7   Hepatomegaly   312 non-null    object
 8   Spiders        312 non-null    object
 9   Edema          418 non-null    object
 10  Bilirubin      418 non-null    float64
 11  Cholesterol    284 non-null    float64
 12  Albumin        418 non-null    float64
 13  Copper         310 non-null    float64
 14  Alk_Phos       312 non-null    float64
 15  SGOT           312 non-null    float64
 16  Tryglicerides  282 non-null    float64
 17  Platelets      407 non-null    float64
 18  Prothrombin    416 non-null    float64
 19  Stage          412 non-null    category
dtypes: category(1), float64(9), int64(3), object(7)
memory usage: 62.8+ KB

### 3.1 Solution: Missing data

1. Use the pandas method `isnull`.

2. Get the number of missing values per column by calling `sum()` on the result of `isnull`. Which features, i.e. columns have missing values?

3. Make a barplot that shows the number of missing values per column.

In [44]:
data_nas = data.isnull().sum() # This gives us how many NA values are there in each column
data_nas

ID                 0
N_Days             0
Status             0
Drug             106
Age                0
Sex                0
Ascites          106
Hepatomegaly     106
Spiders          106
Edema              0
Bilirubin          0
Cholesterol      134
Albumin            0
Copper           108
Alk_Phos         106
SGOT             106
Tryglicerides    136
Platelets         11
Prothrombin        2
Stage              6
dtype: int64

We can see that there are some columns without NA values. If we want to get only the names for the columns that have missing values, we can slice the column names this way:

In [45]:
data.columns[data_nas > 0]

Index(['Drug', 'Ascites', 'Hepatomegaly', 'Spiders', 'Cholesterol', 'Copper',
       'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin',
       'Stage'],
      dtype='object')

In [46]:
# Finally we make a bar plot.
#there is only one column so we do not need to supply an x
fig = px.bar(data_nas, text_auto = True)
fig.update_traces(textangle=0, textposition="outside")
fig.show()

In [47]:
#but we can of course be explicit (and maybe should!)
fig = px.bar(data_nas, y = 0, x = data_nas.index, text_auto = True)
fig.update_traces(textangle=0, textposition="outside")
fig.show()

### 3.2 Solution: Omitting observations with missing values

1. Create a subset in which you omit all patients, i.e. rows, which have missing values in any column. Take care to not overwrite the original dataframe. If you did, you can re-import it.

2. How many observations, i.e. patients, would you be left with if you removed all missing values?

3. How many if you only omit patients where the outcome is missing?

In [48]:
# Let's drop all rows with NAs:

# drop all na values with the dropna() method
df1 = data.dropna() 

# let's check the dimensions of the before and after
print('Reduced data from {} to {}'.format(data.shape, df1.shape))

Reduced data from (418, 20) to (276, 20)

In [49]:
# And now, we filter for rows where the outcome, Stage is not NA
df2 = data.loc[data['Stage'].notna()]
print('Reduced data from {} to {}'.format(data.shape, df2.shape))

df2

Reduced data from (418, 20) to (412, 20)

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.0,2.60,156.0,1718.0,137.95,172.0,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.0,4.14,54.0,7394.8,113.52,88.0,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.0,3.48,210.0,516.0,96.10,55.0,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.0,2.54,64.0,6121.8,60.63,92.0,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.0,3.53,143.0,671.0,113.15,72.0,136.0,10.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,414,681,D,NaN,24472,F,NaN,NaN,NaN,N,1.2,NaN,2.96,NaN,NaN,NaN,NaN,174.0,10.9,3.0
414,415,1103,C,NaN,14245,F,NaN,NaN,NaN,N,0.9,NaN,3.83,NaN,NaN,NaN,NaN,180.0,11.2,4.0
415,416,1055,C,NaN,20819,F,NaN,NaN,NaN,N,1.6,NaN,3.42,NaN,NaN,NaN,NaN,143.0,9.9,3.0
416,417,691,C,NaN,21185,F,NaN,NaN,NaN,N,0.8,NaN,3.75,NaN,NaN,NaN,NaN,269.0,10.4,3.0
417,418,976,C,NaN,19358,F,NaN,NaN,NaN,N,0.7,NaN,3.29,NaN,NaN,NaN,NaN,350.0,10.6,4.0

### Solution: 3.3 Effects of removing data

We can now have a look at how removing nans effects the data.


1. First, plot the correlation coefficient between all numerical columns in the original cirrhosis dataframe. (Analogous to 2.2).

In [50]:
px.imshow(data.corr(numeric_only=True), 
          text_auto = '.2f', color_continuous_scale='IceFire', range_color=[-1,1])

2. Now, remake the plot for the subset where you have removed all rows with any missing data. Have the correlations changed?

In [51]:
px.imshow(df1.corr(numeric_only=True), 
          text_auto = '.2f', color_continuous_scale='IceFire', range_color=[-1,1])

The correlations have changed because we have removed all rows with NAs on them, meaning that some of the calculations between variables were done without using all the possible data points.

### Solution: 3.4 Imputation

Use the method `fillna()` to impute missing values in the columns **where it makes sense**. Have a look at the documentation: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

1. A good way to impute numerical data can be i.e. the mean or median. Calculate the mean for all numerical columns.

In [52]:
# this can be done by first selecting the numeric columns and then appyling .mean() 
num_cols = ['N_Days', 'Age', 'Bilirubin', 'Cholesterol', 'Albumin', 'Copper', 'Alk_Phos', 'SGOT', 'Tryglicerides', 'Platelets', 'Prothrombin']

means_df = data[num_cols].mean()
means_df

N_Days            1917.782297
Age              18533.351675
Bilirubin            3.220813
Cholesterol        369.510563
Albumin              3.497440
Copper              97.648387
Alk_Phos          1982.655769
SGOT               122.556346
Tryglicerides      124.702128
Platelets          257.024570
Prothrombin         10.731731
dtype: float64

1. Perform the imputation.

Since we already have the means of all numeric columns calculated we can also use that in a similar way as shown in the documentation.

In [53]:
mean_dict = means_df.to_dict()
mean_dict

{'N_Days': 1917.7822966507176,
 'Age': 18533.351674641148,
 'Bilirubin': 3.2208133971291866,
 'Cholesterol': 369.51056338028167,
 'Albumin': 3.4974401913875592,
 'Copper': 97.64838709677419,
 'Alk_Phos': 1982.6557692307692,
 'SGOT': 122.55634615384616,
 'Tryglicerides': 124.70212765957447,
 'Platelets': 257.02457002457004,
 'Prothrombin': 10.731730769230769}

In [54]:
df_impute = data.fillna(value=mean_dict)
df_impute

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,1,400,D,D-penicillamine,21464,F,Y,Y,Y,Y,14.5,261.000000,2.60,156.000000,1718.000000,137.950000,172.000000,190.0,12.2,4.0
1,2,4500,C,D-penicillamine,20617,F,N,Y,Y,N,1.1,302.000000,4.14,54.000000,7394.800000,113.520000,88.000000,221.0,10.6,3.0
2,3,1012,D,D-penicillamine,25594,M,N,N,N,S,1.4,176.000000,3.48,210.000000,516.000000,96.100000,55.000000,151.0,12.0,4.0
3,4,1925,D,D-penicillamine,19994,F,N,Y,Y,S,1.8,244.000000,2.54,64.000000,6121.800000,60.630000,92.000000,183.0,10.3,4.0
4,5,1504,CL,Placebo,13918,F,N,Y,Y,N,3.4,279.000000,3.53,143.000000,671.000000,113.150000,72.000000,136.0,10.9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,414,681,D,NaN,24472,F,NaN,NaN,NaN,N,1.2,369.510563,2.96,97.648387,1982.655769,122.556346,124.702128,174.0,10.9,3.0
414,415,1103,C,NaN,14245,F,NaN,NaN,NaN,N,0.9,369.510563,3.83,97.648387,1982.655769,122.556346,124.702128,180.0,11.2,4.0
415,416,1055,C,NaN,20819,F,NaN,NaN,NaN,N,1.6,369.510563,3.42,97.648387,1982.655769,122.556346,124.702128,143.0,9.9,3.0
416,417,691,C,NaN,21185,F,NaN,NaN,NaN,N,0.8,369.510563,3.75,97.648387,1982.655769,122.556346,124.702128,269.0,10.4,3.0
417,418,976,C,NaN,19358,F,NaN,NaN,NaN,N,0.7,369.510563,3.29,97.648387,1982.655769,122.556346,124.702128,350.0,10.6,4.0

2. Re-make the barplot from 3.1. to check that it worked.

In [55]:
data_na =  df_impute.isnull().sum() # calculate again the number of NAs in each column
fig = px.bar(data_na, text_auto= True) # bar plot with text of the NA count
fig.update_traces(textangle=0, textposition="outside") # put the text outside the barplot
fig.show()

We can see that the variables with dtype `object` have not been filled with NAs! This is as intended from our previous for loop

3. Recalculate correlation coefficients between all numerical columns and show it in a heatmap

In [56]:
px.imshow(df_impute.corr(numeric_only=True), 
          text_auto = '.2f', color_continuous_scale='RdBu_r', range_color=[-1,1])